# Controls when the workflow will run
name: Tag on Push

on:
  push:
    branches:
      - 'main'
    paths:
      - 'statefulset.yaml'  # Only trigger when this file is modified
  workflow_dispatch:

permissions:
  contents: write


jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Extract Image Tag
        id: get_tag
        run: |
          IMAGE_TAG=$(grep 'image: zwavejs/zwave-js-ui:' statefulset.yaml | sed 's/.*:\(.*\)$/\1/')
          echo "image_tag=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Create Tag
        if: env.image_tag != ''
        run: |
          git tag "$image_tag"
        
      - name: Push Tag to Repository
        if: env.image_tag != ''
        run: |
          git push origin "$image_tag"
          
      - name: Send message to Slack
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text":"New Z-WaveJS GitHub Tag: '$image_tag'"}' \
          $SLACK_WEBHOOK_URL
